/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agro;


import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author Dahiana Sanchez 6.083.677
 */
public class PedidosCompra extends javax.swing.JFrame {
  Conexion conn = new Conexion();
   javax.swing.table.DefaultTableModel m;
   int ban =0;
  int fac =0;
 
    public PedidosCompra() {
        initComponents();
        m = (javax.swing.table.DefaultTableModel) Ficha.getModel();
        cargaCombo(cboPedido,"SELECT Estado from estadopedido order by Estado");
          m.setRowCount(0);
          lblfecha.setText(fecha());
          txtNro.requestFocus();
    }
        private void cargaCombo(javax.swing.JComboBox cbo, String sql ){
            
       
       try {
           cbo.removeAllItems();
           conn.sentencia = conn.conexion.createStatement();
           conn.resultado = conn.sentencia.executeQuery(sql);
           while (conn.resultado.next())
               cbo.addItem(conn.resultado.getString("Estado"));  
           cbo.setSelectedItem(-1);
       } catch (SQLException ex) {
           Logger.getLogger(PedidosCompra.class.getName()).log(Level.SEVERE, null, ex);
       }
          
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblfecha = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNro = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnPersonal = new javax.swing.JButton();
        txtPersonalid = new javax.swing.JTextField();
        txtPersonal = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtGmail = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        txtArticulo = new javax.swing.JTextField();
        txtArticuloid = new javax.swing.JTextField();
        Cantidad = new javax.swing.JTextField();
        btnBusquedaAR = new javax.swing.JButton();
        aceptar = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Ficha = new javax.swing.JTable();
        btnNuevo = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnGrabar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PEDIDOS");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(0, 102, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("FECHA");

        lblfecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblfecha.setText("00:00:00");

        jLabel3.setText("Nro Documento");

        txtNro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNroKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(txtNro, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblfecha))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Empleados"));

        jLabel7.setText("CI");

        btnPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonalActionPerformed(evt);
            }
        });

        txtPersonalid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPersonalidMousePressed(evt);
            }
        });
        txtPersonalid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPersonalidActionPerformed(evt);
            }
        });
        txtPersonalid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPersonalidKeyPressed(evt);
            }
        });

        jLabel8.setText("Telefono");

        jLabel9.setText("Correo E");

        txtGmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtGmail, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(btnPersonal)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtPersonalid, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(139, 139, 139)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPersonalid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtGmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Detalle Pedido"));

        txtArticulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtArticuloMousePressed(evt);
            }
        });

        txtArticuloid.setToolTipText("Ingrese el codigo del Articulo");
        txtArticuloid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtArticuloidActionPerformed(evt);
            }
        });
        txtArticuloid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtArticuloidKeyPressed(evt);
            }
        });

        Cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CantidadKeyPressed(evt);
            }
        });

        btnBusquedaAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBusquedaARMousePressed(evt);
            }
        });
        btnBusquedaAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaARActionPerformed(evt);
            }
        });
        btnBusquedaAR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnBusquedaARKeyPressed(evt);
            }
        });

        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });
        aceptar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                aceptarKeyPressed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Productos");

        jLabel4.setText("Cantidad");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(btnBusquedaAR, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtArticuloid, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(aceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtArticuloid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnBusquedaAR, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        Ficha.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Descripcion", "Cantidad", "Empleado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Ficha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FichaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(Ficha);

        btnNuevo.setText("Agregar");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnGrabar.setText("Guardar");
        btnGrabar.setToolTipText("Guarde los Datos Ingresados");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });

        jButton1.setText("Modififcar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(btnNuevo)
                        .addGap(30, 30, 30)
                        .addComponent(jButton1)
                        .addGap(30, 30, 30)
                        .addComponent(btnGrabar)
                        .addGap(31, 31, 31)
                        .addComponent(btnSalir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnGrabar)
                    .addComponent(btnSalir)
                    .addComponent(btnNuevo))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonalActionPerformed
      String sql = "SELECT id,  concat(Nombre, ', ', Apellido) Personal,Telefono, Gmail, CI FROM Empleados WHERE id = '" +
                    txtPersonalid.getText()+ "'";
           try {  
            conn.traeDatos(sql);
            if(conn.resultado.next()){
                txtPersonal.setText(conn.resultado.getString("Personal"));
                txtPersonalid.setText(conn.resultado.getString("id"));
                txtGmail.setText(conn.resultado.getString("Gmail"));
                txtTelefono.setText(conn.resultado.getString("Telefono"));
                txtCedula.setText(conn.resultado.getString("CI"));
                
            }
//            
        } catch (SQLException ex) {
            Logger.getLogger(PedidosCompra.class.getName()).log(Level.SEVERE, null, ex);
        }
           txtArticuloid.requestFocus();
    }//GEN-LAST:event_btnPersonalActionPerformed

    private void txtPersonalidMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPersonalidMousePressed
//        Empleados objeto = new Empleados (null, true);
//        objeto.setLocationRelativeTo(null);
//        objeto.setVisible(true);
    }//GEN-LAST:event_txtPersonalidMousePressed

    private void txtPersonalidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPersonalidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPersonalidActionPerformed

    private void txtPersonalidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPersonalidKeyPressed
        txtArticuloid.requestFocus();
    }//GEN-LAST:event_txtPersonalidKeyPressed

    private void txtGmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGmailActionPerformed

    private void txtArticuloidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtArticuloidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtArticuloidActionPerformed

    private void txtArticuloidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtArticuloidKeyPressed

    }//GEN-LAST:event_txtArticuloidKeyPressed

    private void btnBusquedaARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaARActionPerformed
            
        try {
            int a = 0;
            String sql = "SELECT id, Descripcion, Precio FROM Articulo";
            conn.traeDatos(sql + " WHERE id = '" + txtArticuloid.getText() + "'");
            if (!conn.resultado.next()){
                conn.traeDatos(sql + "WHERE CodLocal = '" + txtArticuloid.getText() +"'");
                if (!conn.resultado.next()){
                    conn.traeDatos(sql + "WHERE Barra = '" + txtArticuloid.getText() +"'");
                    if (!conn.resultado.next()){
                        //Por buscar
                        a = 0;

                    }
                }
            }
            if (a ==0){
                txtArticuloid.setText(conn.resultado.getString("id"));
                txtArticulo.setText(conn.resultado.getString("Descripcion"));
                txtPrecio.setText(conn.resultado.getString("Precio"));
                Cantidad.requestFocus();
            }
        } catch (SQLException ex) {
            Logger.getLogger(PedidosCompra.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBusquedaARActionPerformed
         private void cargaFila(){
           int TPro = Integer.parseInt(txtPrecio.getText().trim())* Integer.parseInt(Cantidad.getText().trim());
           m.addRow(new Object[]
           {txtArticuloid.getText(),
               txtArticulo.getText(),
               Cantidad.getText(),
               txtPrecio.getText(),
              
           });
       }  
         private void LimpiaArticulos(){
             txtArticuloid.setText("");
             txtArticulo.setText("");
             Cantidad.setText("");
             txtPrecio.setText("");
             
         }
    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
//        DefaultTableModel m = (DefaultTableModel) Ficha.getModel();
//        m.setRowCount(0);
        Object [] fila=new Object[4];
        fila[0]=txtArticuloid.getText();
        fila[1]=txtArticulo.getText();
        fila[2]=txtPrecio.getText(); 
        fila[3]=Cantidad.getText();
        m.addRow(fila);
//        Ficha.setModel(m);
          calcufila();
          btnGrabar.requestFocus();
    }//GEN-LAST:event_aceptarActionPerformed

    private void aceptarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aceptarKeyPressed
        Object [] fila=new Object[4];
        fila[0]=txtArticuloid.getText();
        fila[1]=txtArticulo.getText();
        fila[2]=txtPrecio.getText(); 
        fila[3]=Cantidad.getText();
        m.addRow(fila);
        calcufila();
         btnGrabar.requestFocus();
          
    }//GEN-LAST:event_aceptarKeyPressed

    private void FichaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FichaKeyPressed
      if(evt.getKeyCode()==KeyEvent.VK_ENTER);
            m.removeRow(Ficha.getSelectedRow());
            calcufila();
             txtArticuloid.requestFocus();
    }//GEN-LAST:event_FichaKeyPressed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
//      desabilita();
        try {
          cboPedido.requestFocus();
          limpiar();
          String sql = "SELECT max(NroFactura) + 1 as  newReg from pedidos"; // "where nroDepito = " + txtNDeposito.getText()
          conn.traeDatos(sql);
          if (conn.resultado.next())
              txtNro.setText( conn.resultado.getString("NewReg"));
      } catch (SQLException ex) {
          Logger.getLogger(PedidosCompra.class.getName()).log(Level.SEVERE, null, ex);
      }
    }//GEN-LAST:event_btnNuevoActionPerformed
//    private void desabilita(){
//        btnNuevo.setEnabled(true);
//        btnGrabar.setEnabled(true);
//        btnSalir.setEnabled(true);
//    
//    }
    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed

      try {
          int Estado = traeCod("Select id from estadopedido where estado = '" + cboPedido.getSelectedItem() + "'");
          String sql = "SELECT max(id) + 1 as  newReg from pedidos";
          conn.traeDatos(sql);
          if (conn.resultado.next()){
             fac= conn.resultado.getInt("NewReg");
              sql= "INSERT INTO pedidos (id, fecha,  Empleadoid,NroFactura,  estadopedidoid ) VALUES ("
                + fac +", DATE(NOW()) ," + txtPersonalid.getText() +","+txtNro.getText()   +","+  Estado +") ";
              System.out.println(sql);
              JOptionPane.showMessageDialog(this, "Datos Guardados Correctamente " );
              conn.actualizaTabla(sql);
              guardaMovi();
          } 
      } catch (SQLException ex) {
          Logger.getLogger(PedidosCompra.class.getName()).log(Level.SEVERE, null, ex);
      }
    }//GEN-LAST:event_btnGrabarActionPerformed
     
    
    private int traeCod(String sql){
       int cod = 0;
        try {
           
           conn.traeDatos(sql);
           if(conn.resultado.next())
               cod = conn.resultado.getInt(1);
           
       } catch (SQLException ex) {
           Logger.getLogger(PedidosCompra.class.getName()).log(Level.SEVERE, null, ex);
           
       }
        return cod;
    }
    private void txtNroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNroKeyPressed
       cboPedido.requestFocus();
    }//GEN-LAST:event_txtNroKeyPressed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
      dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnBusquedaARMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBusquedaARMousePressed
        
    }//GEN-LAST:event_btnBusquedaARMousePressed

    private void btnBusquedaARKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnBusquedaARKeyPressed
       
        try {
            int a = 0;
            String sql = "SELECT id, Descripcion, Precio FROM Articulo";
            conn.traeDatos(sql + " WHERE id = '" + txtArticuloid.getText() + "'");
            if (!conn.resultado.next()){
                conn.traeDatos(sql + "WHERE CodLocal = '" + txtArticuloid.getText() +"'");
                if (!conn.resultado.next()){
                    conn.traeDatos(sql + "WHERE Barra = '" + txtArticuloid.getText() +"'");
                    if (!conn.resultado.next()){
                        //Por buscar
                        a = 0;

                    }
                }
            }
            if (a ==0){
                txtArticuloid.setText(conn.resultado.getString("id"));
                txtArticulo.setText(conn.resultado.getString("Descripcion"));
                txtPrecio.setText(conn.resultado.getString("Precio"));
                Cantidad.requestFocus();
            }
        } catch (SQLException ex) {
            Logger.getLogger(PedidosCompra.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBusquedaARKeyPressed

    private void CantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CantidadKeyPressed
       
    }//GEN-LAST:event_CantidadKeyPressed

    private void txtArticuloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtArticuloMousePressed
         ProductosB objeto = new ProductosB (null, true);
        objeto.setLocationRelativeTo(null);
        objeto.setVisible(true);
    }//GEN-LAST:event_txtArticuloMousePressed
//     private void InsertaDato(){
//       String sql ="Insert into Articulo ( Desccripcion, Precio) "
//               + "values('"+ txtArticuloid.getText() + "', '"+ txtArticuloid.getText() + "', '" + txtPrecio.getText() +"')";
//       System.out.println(sql);
//       conn.actualizaTabla(sql);
//     }
     private void guardaMovi(){
         int cf = m.getRowCount();
          for(int i = 0; i<cf; i++){
         String sql = "INSERT INTO detallepedido(id,  pedidosid, Articuloid, Precio, Cantidad) VALUES (" + fac 
                 + "," + m.getValueAt(i, 0).toString() + "," + m.getValueAt(i, 0).toString()+ "," + m.getValueAt(i,2).toString() +
                    ","+m.getValueAt(i, 3).toString()+")";
          conn.actualizaTabla(sql); //detalle compra
          System.out.print(sql);
          
          }  
     }   
    private void limpiar(){
        txtPersonalid.setText("");
        txtPersonal.setText("");
        txtGmail.setText("");
        txtTelefono.setText("");
        txtCedula.setText("");
        txtArticulo.setText("");
        txtArticuloid.setText("");
        txtPrecio.setText("");
        Cantidad.setText("");
        m.setRowCount(0);
  
        
    }
    private void calcufila(){
        if(Cantidad.getText().trim().equals(""))Cantidad.setText("1");
       if(txtPrecio.getText().trim().equals(""))
           txtPrecio.requestFocus();
       else{
           LimpiaArticulos();
        txtArticuloid.requestFocus();
       }
    }
    public static String fecha(){
Date fecha=new Date();
SimpleDateFormat formatofecha = new SimpleDateFormat("yyyy/MM/dd");
return formatofecha.format(fecha);
 } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PedidosCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PedidosCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PedidosCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PedidosCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PedidosCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField Cantidad;
    private javax.swing.JTable Ficha;
    private javax.swing.JButton aceptar;
    private javax.swing.JButton btnBusquedaAR;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnPersonal;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblfecha;
    public static javax.swing.JTextField txtArticulo;
    public static javax.swing.JTextField txtArticuloid;
    public static javax.swing.JTextField txtCedula;
    public static javax.swing.JTextField txtGmail;
    private javax.swing.JTextField txtNro;
    public static javax.swing.JTextField txtPersonal;
    public static javax.swing.JTextField txtPersonalid;
    public static javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
